---

- name: Provision a {{ application_name }} server
  hosts: all
  sudo: yes
  sudo_user: root
  remote_user: "{{ssh_user}}"
  vars:
    - update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/secure.yml
  roles:
    - { role: swapfile, tags: ['swapfile'], when: swapon == true}
    - { role: base, tags: ['base'] }
    - { role: memcached, tags: ['memcached'] }